# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-17 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20171130_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='course_1',
            field=models.BooleanField(default=False),
        ),
    ]
