# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-17 20:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_course_1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='course_1',
            new_name='answer_1',
        ),
    ]
