# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-17 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20171217_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='answer_1',
            field=models.IntegerField(default=False),
        ),
    ]
