# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-17 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20171217_2048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answers',
            name='user',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='answer_1',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Answers',
        ),
    ]
