# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-22 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20171217_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='answer_1',
            field=models.CharField(max_length=50),
        ),
    ]
