# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-24 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20171222_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='answer_1_check',
            field=models.BooleanField(default=False),
        ),
    ]
