# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-01 00:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_userprofile_answer_1_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='answer_2',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='answer_2_check',
            field=models.BooleanField(default=False),
        ),
    ]
