# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-01 00:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20180101_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='answer_3',
            field=models.CharField(default=50, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='answer_3_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='answer_4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='answer_4_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='answer_2',
            field=models.IntegerField(default=0),
        ),
    ]
