# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-01 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20180101_0651'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='answer_10',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='answer_10_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='answer_11',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='answer_11_check',
            field=models.BooleanField(default=False),
        ),
    ]
