# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-01 08:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20180101_0755'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='answer_1',
            new_name='answer_1_1',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='answer_10_check',
            new_name='answer_1_1_check',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='answer_2',
            new_name='answer_1_2',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='answer_11_check',
            new_name='answer_1_2_check',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='answer_10',
            new_name='answer_1_3',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='answer_2_check',
            new_name='answer_1_3_check',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='answer_4',
            new_name='answer_1_4',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='answer_1_check',
            new_name='answer_1_4_check',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='answer_11',
            new_name='answer_2_1',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='answer_3_check',
            new_name='answer_2_1_check',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='answer_3',
            new_name='answer_2_2',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='answer_4_check',
            new_name='answer_2_2_check',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='answer_7',
            new_name='answer_2_3',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='answer_5_check',
            new_name='answer_2_3_check',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='answer_5',
            new_name='answer_2_4',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='answer_6_check',
            new_name='answer_2_4_check',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='answer_6',
            new_name='answer_2_5',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='answer_7_check',
            new_name='answer_2_5_check',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='answer_8',
            new_name='answer_3_1',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='answer_8_check',
            new_name='answer_3_1_check',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='answer_9',
            new_name='answer_3_2',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='answer_9_check',
            new_name='answer_3_2_check',
        ),
    ]
