# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-01 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20180101_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='answer_5_1',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='answer_5_1_check',
            field=models.BooleanField(default=False),
        ),
    ]
