# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-01 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_auto_20180101_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='answer_7_2',
            field=models.IntegerField(default=0),
        ),
    ]
